/**
 * 시드 데이터.
 *
 * README 명시: "샘플 데이터(인물·회의체·지시 내용)는 전부 가상입니다. 실제 데이터로 교체하세요."
 * 1~8번은 프로토타입(`전략 Assistant To-do v2.dc.html`)의 RAW 배열을 그대로 옮긴 것이고,
 * 이후 항목은 페이지네이션·집계가 실제로 동작하는지 보기 위해 같은 인물/회의체로 확장한 것이다.
 */
import type { Todo, TodoInput } from "../domain/todo";
import type { TodoUpdate } from "../domain/todo-update";

const ATTACHED = { name: "첨부자료.pdf", size: 284_160 };

// 시드 인물은 가상이라 메일 주소를 두지 않는다 — 실제 주소는 직접 입력한다.
type SeedRow = Omit<TodoInput, "attachment" | "assigneeEmail"> & {
  attachment?: Todo["attachment"];
  assigneeEmail?: string | null;
};

const ROWS: SeedRow[] = [
  {
    instructedAt: "2026-08-05",
    dueDate: "2026-08-14",
    meetingBody: "주간 경영회의",
    org: "영업본부",
    assigneeName: "박현수 본부장",
    category: "전략검토",
    detail: "동남아 신규 채널 진입안 — 채널별 마진 시나리오 포함 보고",
    progressNote: "초안 작성 중 · 8/19 중간 공유",
    signal: "Y",
    remindStatus: "wait",
    attachment: ATTACHED,
  },
  {
    instructedAt: "2026-07-29",
    dueDate: "2026-08-08",
    meetingBody: "사업전략 점검회의",
    org: "생산본부",
    assigneeName: "정민아 실장",
    category: "이행점검",
    detail: "3라인 증설 투자 회수기간 재산정 및 대안 2안 제시",
    progressNote: "자료 확보 지연 · 재무팀 협의 필요",
    signal: "R",
    remindStatus: "sent",
    attachment: ATTACHED,
  },
  {
    instructedAt: "2026-08-10",
    dueDate: "2026-08-20",
    meetingBody: "주간 경영회의",
    org: "경영기획실",
    assigneeName: "김도현 COO",
    category: "의사결정",
    detail: "하반기 인력 운영계획 — 본부별 정원 조정안 확정",
    progressNote: "본부 취합 완료 · 검토 중",
    signal: "G",
    remindStatus: "sent",
  },
  {
    instructedAt: "2026-08-11",
    dueDate: "2026-08-13",
    meetingBody: "임원 조회",
    org: "DT추진실",
    assigneeName: "이수영 실장",
    category: "자료요청",
    detail: "그룹사 AI 도입 사례 벤치마킹 자료 취합",
    progressNote: "미착수",
    signal: "R",
    remindStatus: "wait",
    attachment: ATTACHED,
  },
  {
    instructedAt: "2026-08-04",
    dueDate: "2026-08-18",
    meetingBody: "월간 실적회의",
    org: "영업본부",
    assigneeName: "박현수 본부장",
    category: "이행점검",
    detail: "7월 미달 거래처 회복 계획 및 담당 재배치",
    progressNote: "계획 수립 완료 · 실행 착수",
    signal: "G",
    remindStatus: "none",
  },
  {
    instructedAt: "2026-07-31",
    dueDate: "2026-08-15",
    meetingBody: "사업전략 점검회의",
    org: "경영기획실",
    assigneeName: "한지훈 팀장",
    category: "대외대응",
    detail: "규제 변경 관련 대외 커뮤니케이션 초안 및 예상 질의 정리",
    progressNote: "법무 검토 회신 대기",
    signal: "Y",
    remindStatus: "wait",
    attachment: ATTACHED,
  },
  {
    instructedAt: "2026-08-06",
    dueDate: "2026-08-28",
    meetingBody: "주간 경영회의",
    org: "생산본부",
    assigneeName: "정민아 실장",
    category: "전략검토",
    detail: "원가 절감 3개년 로드맵 — 항목별 절감액 근거 보완",
    progressNote: "부서 의견 수렴 중",
    signal: "G",
    remindStatus: "none",
  },
  {
    instructedAt: "2026-08-12",
    dueDate: "2026-08-19",
    meetingBody: "임원 조회",
    org: "인사팀",
    assigneeName: "최은정 팀장",
    category: "자료요청",
    detail: "핵심인재 이탈률 및 리텐션 프로그램 효과 분석",
    progressNote: "등록 직후 · 담당 통보 예정",
    signal: "Y",
    remindStatus: "wait",
  },

  // ── 이하 확장분 ──────────────────────────────────────────────
  {
    instructedAt: "2026-08-07",
    dueDate: "2026-08-17",
    meetingBody: "주간 경영회의",
    org: "영업본부",
    assigneeName: "박현수 본부장",
    category: "자료요청",
    detail: "상반기 대리점 이탈 사유 분석 및 재계약 조건 비교표",
    progressNote: "지역별 취합 60% 진행",
    signal: "Y",
    remindStatus: "wait",
  },
  {
    instructedAt: "2026-07-27",
    dueDate: "2026-08-10",
    meetingBody: "수시 지시 (메일)",
    org: "DT추진실",
    assigneeName: "이수영 실장",
    category: "이행점검",
    detail: "전사 데이터 거버넌스 체계 수립 1단계 이행 현황 점검",
    progressNote: "표준 정의 지연 · 현업 협조 요청 중",
    signal: "R",
    remindStatus: "sent",
    attachment: ATTACHED,
  },
  {
    instructedAt: "2026-08-03",
    dueDate: "2026-08-21",
    meetingBody: "월간 실적회의",
    org: "경영기획실",
    assigneeName: "김도현 COO",
    category: "전략검토",
    detail: "2027년 중기 사업계획 전제 조건 재설정 — 환율·원자재 민감도",
    progressNote: "시나리오 3안 초안 완료",
    signal: "G",
    remindStatus: "none",
  },
  {
    instructedAt: "2026-08-08",
    dueDate: "2026-08-14",
    meetingBody: "사업전략 점검회의",
    org: "인사팀",
    assigneeName: "최은정 팀장",
    category: "의사결정",
    detail: "성과급 지급 기준 개편안 — 본부별 배분 방식 확정 필요",
    progressNote: "노경협의회 안건 상정 준비",
    signal: "Y",
    remindStatus: "wait",
    attachment: ATTACHED,
  },
  {
    instructedAt: "2026-07-24",
    dueDate: "2026-08-07",
    meetingBody: "주간 경영회의",
    org: "생산본부",
    assigneeName: "정민아 실장",
    category: "대외대응",
    detail: "협력사 단가 인상 요청 대응 논리 및 수용 범위 정리",
    progressNote: "구매팀 회신 지연",
    signal: "R",
    remindStatus: "sent",
  },
  {
    instructedAt: "2026-08-09",
    dueDate: "2026-08-26",
    meetingBody: "임원 조회",
    org: "경영기획실",
    assigneeName: "한지훈 팀장",
    category: "자료요청",
    detail: "경쟁사 3사 최근 4개 분기 수익성 추이 비교 자료",
    progressNote: "공시 자료 수집 완료",
    signal: "G",
    remindStatus: "none",
  },
  {
    instructedAt: "2026-08-11",
    dueDate: "2026-08-25",
    meetingBody: "월간 실적회의",
    org: "영업본부",
    assigneeName: "박현수 본부장",
    category: "의사결정",
    detail: "국내 유통 채널 재편안 — 직영 전환 대상 확정",
    progressNote: "손익 시뮬레이션 검토 중",
    signal: "Y",
    remindStatus: "wait",
  },
  {
    instructedAt: "2026-07-30",
    dueDate: "2026-08-11",
    meetingBody: "수시 지시 (메일)",
    org: "인사팀",
    assigneeName: "최은정 팀장",
    category: "이행점검",
    detail: "조직개편 후속 인사이동 완료 여부 및 잔여 과제 보고",
    progressNote: "3개 본부 미완료",
    signal: "R",
    remindStatus: "wait",
  },
  {
    instructedAt: "2026-08-12",
    dueDate: "2026-09-02",
    meetingBody: "주간 경영회의",
    org: "DT추진실",
    assigneeName: "이수영 실장",
    category: "전략검토",
    detail: "생성형 AI 사내 적용 우선순위 과제 5건 선정 및 ROI 추정",
    progressNote: "등록 직후 · 담당 통보 예정",
    signal: "G",
    remindStatus: "wait",
  },
  {
    instructedAt: "2026-08-01",
    dueDate: "2026-08-16",
    meetingBody: "사업전략 점검회의",
    org: "경영기획실",
    assigneeName: "김도현 COO",
    category: "이행점검",
    detail: "전사 비용 절감 목표 대비 본부별 실적 점검 및 미달 사유",
    progressNote: "3개 본부 소명 자료 대기",
    signal: "Y",
    remindStatus: "sent",
  },
  {
    instructedAt: "2026-07-22",
    dueDate: "2026-08-05",
    meetingBody: "월간 실적회의",
    org: "생산본부",
    assigneeName: "정민아 실장",
    category: "자료요청",
    detail: "설비 가동률 하락 구간 원인 분석 데이터",
    progressNote: "분석 완료 · 보고서 정리 중",
    signal: "Y",
    remindStatus: "sent",
    attachment: ATTACHED,
  },
  {
    instructedAt: "2026-08-10",
    dueDate: "2026-08-24",
    meetingBody: "임원 조회",
    org: "영업본부",
    assigneeName: "박현수 본부장",
    category: "대외대응",
    detail: "주요 고객사 클레임 대응 경과 및 재발 방지책",
    progressNote: "고객사 방문 일정 조율",
    signal: "G",
    remindStatus: "none",
  },
  {
    instructedAt: "2026-08-05",
    dueDate: "2026-08-13",
    meetingBody: "수시 지시 (메일)",
    org: "경영기획실",
    assigneeName: "한지훈 팀장",
    category: "의사결정",
    detail: "신규 투자 심의 안건 — 심의위 상정 여부 판단",
    progressNote: "재무 검토 회신 대기",
    signal: "R",
    remindStatus: "wait",
  },
  {
    instructedAt: "2026-08-06",
    dueDate: "2026-08-31",
    meetingBody: "주간 경영회의",
    org: "인사팀",
    assigneeName: "최은정 팀장",
    category: "전략검토",
    detail: "차세대 리더 후보군 선발 기준 및 육성 트랙 설계",
    progressNote: "벤치마킹 자료 검토 중",
    signal: "G",
    remindStatus: "none",
  },
  {
    instructedAt: "2026-07-28",
    dueDate: "2026-08-12",
    meetingBody: "사업전략 점검회의",
    org: "DT추진실",
    assigneeName: "이수영 실장",
    category: "의사결정",
    detail: "레거시 ERP 교체 범위 확정 — 단계적 전환 vs 일괄 전환",
    progressNote: "현업 요구사항 정리 완료 · 의사결정 대기",
    signal: "Y",
    remindStatus: "wait",
    attachment: ATTACHED,
  },
  {
    instructedAt: "2026-08-04",
    dueDate: "2026-08-27",
    meetingBody: "월간 실적회의",
    org: "생산본부",
    assigneeName: "정민아 실장",
    category: "의사결정",
    detail: "외주 공정 내재화 대상 선정 및 투자 규모 검토",
    progressNote: "원가 비교 진행 중",
    signal: "G",
    remindStatus: "none",
  },
  {
    instructedAt: "2026-08-03",
    dueDate: "2026-08-09",
    meetingBody: "임원 조회",
    org: "경영기획실",
    assigneeName: "김도현 COO",
    category: "대외대응",
    detail: "IR 대응 자료 — 하반기 가이던스 조정 관련 예상 질의",
    progressNote: "초안 회람 · 최종 확정 지연",
    signal: "R",
    remindStatus: "sent",
  },
  {
    instructedAt: "2026-07-25",
    dueDate: "2026-08-06",
    meetingBody: "수시 지시 (메일)",
    org: "영업본부",
    assigneeName: "박현수 본부장",
    category: "이행점검",
    detail: "판촉비 집행 현황 점검 및 잔여 예산 재배분",
    progressNote: "집행 내역 확정 · 재배분안 보고 완료",
    signal: "G",
    remindStatus: "sent",
  },
];

/**
 * 시드 To-do 배열. id/타임스탬프는 결정적으로 생성한다 —
 * 서버가 재시작해도 같은 id가 나와야 링크·테스트가 깨지지 않는다.
 */
export const SEED_TODOS: Todo[] = ROWS.map((row, i) => ({
  ...row,
  attachment: row.attachment ?? null,
  assigneeEmail: row.assigneeEmail ?? null,
  id: `seed-${String(i + 1).padStart(3, "0")}`,
  createdAt: `${row.instructedAt}T09:00:00.000Z`,
  updatedAt: `${row.instructedAt}T09:00:00.000Z`,
}));

/**
 * 시드 진행 이력.
 *
 * 마이그레이션의 백필과 같은 규칙이다 — 진행상황이 적힌 지시사항은
 * 그 내용을 첫 이력으로 갖는다. 인메모리 어댑터에서도 펼침 화면이
 * 비어 보이지 않도록 맞춘다.
 */
export const SEED_TODO_UPDATES: TodoUpdate[] = SEED_TODOS.filter(
  (t) => t.progressNote.trim() !== "",
).map((t, i) => ({
  id: `seed-upd-${String(i + 1).padStart(3, "0")}`,
  todoId: t.id,
  note: t.progressNote,
  signal: t.signal,
  author: null,
  createdAt: t.createdAt,
}));

/**
 * 이번 주 회의 일정.
 * README의 To-do 필드 목록에 회의 일정 테이블이 없어 아직 정적 데이터로 둔다.
 * 회의체 마스터가 생기면 리포지토리로 옮길 것.
 */
export const MEETING_SCHEDULE = [
  { date: "2026-08-13", name: "주간 경영회의", note: "미결 6건 사전 정리" },
  { date: "2026-08-14", name: "사업전략 점검회의", note: "지연 2건 보고" },
  { date: "2026-08-17", name: "월간 실적회의", note: "" },
] as const;
